export const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", timezones: ["Asia/Kabul"] },
  { name: "Albania", code: "AL", flag: "🇦🇱", timezones: ["Europe/Tirane"] },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", timezones: ["Africa/Algiers"] },
  { name: "Andorra", code: "AD", flag: "🇦🇩", timezones: ["Europe/Andorra"] },
  { name: "Angola", code: "AO", flag: "🇦🇴", timezones: ["Africa/Luanda"] },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", timezones: ["America/Antigua"] },
  { name: "Argentina", code: "AR", flag: "🇦🇷", timezones: ["America/Argentina/Buenos_Aires"] },
  { name: "Armenia", code: "AM", flag: "🇦🇲", timezones: ["Asia/Yerevan"] },
  { name: "Australia", code: "AU", flag: "🇦🇺", timezones: ["Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane", "Australia/Perth", "Australia/Adelaide", "Australia/Darwin", "Australia/Hobart"] },
  { name: "Austria", code: "AT", flag: "🇦🇹", timezones: ["Europe/Vienna"] },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", timezones: ["Asia/Baku"] },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", timezones: ["America/Nassau"] },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", timezones: ["Asia/Bahrain"] },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", timezones: ["Asia/Dhaka"] },
  { name: "Barbados", code: "BB", flag: "🇧🇧", timezones: ["America/Barbados"] },
  { name: "Belarus", code: "BY", flag: "🇧🇾", timezones: ["Europe/Minsk"] },
  { name: "Belgium", code: "BE", flag: "🇧🇪", timezones: ["Europe/Brussels"] },
  { name: "Belize", code: "BZ", flag: "🇧🇿", timezones: ["America/Belize"] },
  { name: "Benin", code: "BJ", flag: "🇧🇯", timezones: ["Africa/Porto-Novo"] },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", timezones: ["Asia/Thimphu"] },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", timezones: ["America/La_Paz"] },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", timezones: ["Europe/Sarajevo"] },
  { name: "Botswana", code: "BW", flag: "🇧🇼", timezones: ["Africa/Gaborone"] },
  { name: "Brazil", code: "BR", flag: "🇧🇷", timezones: ["America/Sao_Paulo", "America/Manaus", "America/Belem", "America/Rio_Branco"] },
  { name: "Brunei", code: "BN", flag: "🇧🇳", timezones: ["Asia/Brunei"] },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", timezones: ["Europe/Sofia"] },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", timezones: ["Africa/Ouagadougou"] },
  { name: "Burundi", code: "BI", flag: "🇧🇮", timezones: ["Africa/Bujumbura"] },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻", timezones: ["Atlantic/Cape_Verde"] },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", timezones: ["Asia/Phnom_Penh"] },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", timezones: ["Africa/Douala"] },
  { name: "Canada", code: "CA", flag: "🇨🇦", timezones: ["America/Toronto", "America/Vancouver", "America/Halifax", "America/Winnipeg", "America/Edmonton", "America/St_Johns"] },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫", timezones: ["Africa/Bangui"] },
  { name: "Chad", code: "TD", flag: "🇹🇩", timezones: ["Africa/Ndjamena"] },
  { name: "Chile", code: "CL", flag: "🇨🇱", timezones: ["America/Santiago"] },
  { name: "China", code: "CN", flag: "🇨🇳", timezones: ["Asia/Shanghai"] },
  { name: "Colombia", code: "CO", flag: "🇨🇴", timezones: ["America/Bogota"] },
  { name: "Comoros", code: "KM", flag: "🇰🇲", timezones: ["Indian/Comoro"] },
  { name: "Congo", code: "CG", flag: "🇨🇬", timezones: ["Africa/Brazzaville"] },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", timezones: ["America/Costa_Rica"] },
  { name: "Croatia", code: "HR", flag: "🇭🇷", timezones: ["Europe/Zagreb"] },
  { name: "Cuba", code: "CU", flag: "🇨🇺", timezones: ["America/Havana"] },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", timezones: ["Asia/Nicosia"] },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", timezones: ["Europe/Prague"] },
  { name: "Denmark", code: "DK", flag: "🇩🇰", timezones: ["Europe/Copenhagen"] },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", timezones: ["Africa/Djibouti"] },
  { name: "Dominica", code: "DM", flag: "🇩🇲", timezones: ["America/Dominica"] },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", timezones: ["America/Santo_Domingo"] },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", timezones: ["America/Guayaquil"] },
  { name: "Egypt", code: "EG", flag: "🇪🇬", timezones: ["Africa/Cairo"] },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", timezones: ["America/El_Salvador"] },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", timezones: ["Africa/Malabo"] },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", timezones: ["Africa/Asmara"] },
  { name: "Estonia", code: "EE", flag: "🇪🇪", timezones: ["Europe/Tallinn"] },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿", timezones: ["Africa/Mbabane"] },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", timezones: ["Africa/Addis_Ababa"] },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", timezones: ["Pacific/Fiji"] },
  { name: "Finland", code: "FI", flag: "🇫🇮", timezones: ["Europe/Helsinki"] },
  { name: "France", code: "FR", flag: "🇫🇷", timezones: ["Europe/Paris"] },
  { name: "Gabon", code: "GA", flag: "🇬🇦", timezones: ["Africa/Libreville"] },
  { name: "Gambia", code: "GM", flag: "🇬🇲", timezones: ["Africa/Banjul"] },
  { name: "Georgia", code: "GE", flag: "🇬🇪", timezones: ["Asia/Tbilisi"] },
  { name: "Germany", code: "DE", flag: "🇩🇪", timezones: ["Europe/Berlin"] },
  { name: "Ghana", code: "GH", flag: "🇬🇭", timezones: ["Africa/Accra"] },
  { name: "Greece", code: "GR", flag: "🇬🇷", timezones: ["Europe/Athens"] },
  { name: "Grenada", code: "GD", flag: "🇬🇩", timezones: ["America/Grenada"] },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", timezones: ["America/Guatemala"] },
  { name: "Guinea", code: "GN", flag: "🇬🇺", timezones: ["Africa/Conakry"] },
  { name: "Guyana", code: "GY", flag: "🇬🇾", timezones: ["America/Guyana"] },
  { name: "Haiti", code: "HT", flag: "🇭🇹", timezones: ["America/Port-au-Prince"] },
  { name: "Honduras", code: "HN", flag: "🇭🇳", timezones: ["America/Tegucigalpa"] },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰", timezones: ["Asia/Hong_Kong"] },
  { name: "Hungary", code: "HU", flag: "🇭🇺", timezones: ["Europe/Budapest"] },
  { name: "Iceland", code: "IS", flag: "🇮🇸", timezones: ["Atlantic/Reykjavik"] },
  { name: "India", code: "IN", flag: "🇮🇳", timezones: ["Asia/Kolkata"] },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", timezones: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"] },
  { name: "Iran", code: "IR", flag: "🇮🇷", timezones: ["Asia/Tehran"] },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", timezones: ["Asia/Baghdad"] },
  { name: "Ireland", code: "IE", flag: "🇮🇪", timezones: ["Europe/Dublin"] },
  { name: "Israel", code: "IL", flag: "🇮🇱", timezones: ["Asia/Jerusalem"] },
  { name: "Italy", code: "IT", flag: "🇮🇹", timezones: ["Europe/Rome"] },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", timezones: ["America/Jamaica"] },
  { name: "Japan", code: "JP", flag: "🇯🇵", timezones: ["Asia/Tokyo"] },
  { name: "Jordan", code: "JO", flag: "🇯🇴", timezones: ["Asia/Amman"] },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", timezones: ["Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe"] },
  { name: "Kenya", code: "KE", flag: "🇰🇪", timezones: ["Africa/Nairobi"] },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", timezones: ["Pacific/Tarawa"] },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", timezones: ["Asia/Kuwait"] },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", timezones: ["Asia/Bishkek"] },
  { name: "Laos", code: "LA", flag: "🇱🇦", timezones: ["Asia/Vientiane"] },
  { name: "Latvia", code: "LV", flag: "🇱🇻", timezones: ["Europe/Riga"] },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", timezones: ["Asia/Beirut"] },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", timezones: ["Africa/Maseru"] },
  { name: "Liberia", code: "LR", flag: "🇱🇷", timezones: ["Africa/Monrovia"] },
  { name: "Libya", code: "LY", flag: "🇱🇾", timezones: ["Africa/Tripoli"] },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", timezones: ["Europe/Vaduz"] },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", timezones: ["Europe/Vilnius"] },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", timezones: ["Europe/Luxembourg"] },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", timezones: ["Indian/Antananarivo"] },
  { name: "Malawi", code: "MW", flag: "🇲🇼", timezones: ["Africa/Blantyre"] },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", timezones: ["Asia/Kuala_Lumpur"] },
  { name: "Maldives", code: "MV", flag: "🇲🇻", timezones: ["Indian/Maldives"] },
  { name: "Mali", code: "ML", flag: "🇲🇱", timezones: ["Africa/Bamako"] },
  { name: "Malta", code: "MT", flag: "🇲🇹", timezones: ["Europe/Malta"] },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", timezones: ["Pacific/Majuro"] },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", timezones: ["Africa/Nouakchott"] },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", timezones: ["Indian/Mauritius"] },
  { name: "Mexico", code: "MX", flag: "🇲🇽", timezones: ["America/Mexico_City", "America/Monterrey", "America/Tijuana"] },
  { name: "Micronesia", code: "FM", flag: "🇫🇲", timezones: ["Pacific/Pohnpei"] },
  { name: "Moldova", code: "MD", flag: "🇲🇩", timezones: ["Europe/Chisinau"] },
  { name: "Monaco", code: "MC", flag: "🇲🇨", timezones: ["Europe/Monaco"] },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", timezones: ["Asia/Ulaanbaatar"] },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", timezones: ["Europe/Podgorica"] },
  { name: "Morocco", code: "MA", flag: "🇲🇦", timezones: ["Africa/Casablanca"] },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", timezones: ["Africa/Maputo"] },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", timezones: ["Asia/Yangon"] },
  { name: "Namibia", code: "NA", flag: "🇳🇦", timezones: ["Africa/Windhoek"] },
  { name: "Nauru", code: "NR", flag: "🇳🇷", timezones: ["Pacific/Nauru"] },
  { name: "Nepal", code: "NP", flag: "🇳🇵", timezones: ["Asia/Kathmandu"] },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", timezones: ["Europe/Amsterdam"] },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", timezones: ["Pacific/Auckland"] },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", timezones: ["America/Managua"] },
  { name: "Niger", code: "NE", flag: "🇳🇪", timezones: ["Africa/Niamey"] },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", timezones: ["Africa/Lagos"] },
  { name: "North Korea", code: "KP", flag: "🇰🇵", timezones: ["Asia/Pyongyang"] },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", timezones: ["Europe/Skopje"] },
  { name: "Norway", code: "NO", flag: "🇳🇴", timezones: ["Europe/Oslo"] },
  { name: "Oman", code: "OM", flag: "🇴🇲", timezones: ["Asia/Muscat"] },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", timezones: ["Asia/Karachi"] },
  { name: "Palau", code: "PW", flag: "🇵🇼", timezones: ["Pacific/Palau"] },
  { name: "Panama", code: "PA", flag: "🇵🇦", timezones: ["America/Panama"] },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", timezones: ["Pacific/Port_Moresby"] },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", timezones: ["America/Asuncion"] },
  { name: "Peru", code: "PE", flag: "🇵🇪", timezones: ["America/Lima"] },
  { name: "Philippines", code: "PH", flag: "🇵🇭", timezones: ["Asia/Manila"] },
  { name: "Poland", code: "PL", flag: "🇵🇱", timezones: ["Europe/Warsaw"] },
  { name: "Portugal", code: "PT", flag: "🇵🇹", timezones: ["Europe/Lisbon"] },
  { name: "Qatar", code: "QA", flag: "🇶🇦", timezones: ["Asia/Qatar"] },
  { name: "Romania", code: "RO", flag: "🇷🇴", timezones: ["Europe/Bucharest"] },
  { name: "Russia", code: "RU", flag: "🇷🇺", timezones: ["Europe/Moscow", "Asia/Yekaterinburg", "Asia/Novosibirsk", "Asia/Vladivostok"] },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", timezones: ["Africa/Kigali"] },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", timezones: ["America/St_Kitts"] },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", timezones: ["America/St_Lucia"] },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", timezones: ["America/St_Vincent"] },
  { name: "Samoa", code: "WS", flag: "🇼🇸", timezones: ["Pacific/Apia"] },
  { name: "San Marino", code: "SM", flag: "🇸🇲", timezones: ["Europe/San_Marino"] },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", timezones: ["Africa/Sao_Tome"] },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", timezones: ["Asia/Riyadh"] },
  { name: "Senegal", code: "SN", flag: "🇸🇳", timezones: ["Africa/Dakar"] },
  { name: "Serbia", code: "RS", flag: "🇷🇸", timezones: ["Europe/Belgrade"] },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", timezones: ["Indian/Mahe"] },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", timezones: ["Africa/Freetown"] },
  { name: "Singapore", code: "SG", flag: "🇸🇬", timezones: ["Asia/Singapore"] },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", timezones: ["Europe/Bratislava"] },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", timezones: ["Europe/Ljubljana"] },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", timezones: ["Pacific/Guadalcanal"] },
  { name: "Somalia", code: "SO", flag: "🇸🇴", timezones: ["Africa/Mogadishu"] },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", timezones: ["Africa/Johannesburg"] },
  { name: "South Korea", code: "KR", flag: "🇰🇷", timezones: ["Asia/Seoul"] },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", timezones: ["Africa/Juba"] },
  { name: "Spain", code: "ES", flag: "🇪🇸", timezones: ["Europe/Madrid"] },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", timezones: ["Asia/Colombo"] },
  { name: "Sudan", code: "SD", flag: "🇸🇩", timezones: ["Africa/Khartoum"] },
  { name: "Suriname", code: "SR", flag: "🇸🇷", timezones: ["America/Paramaribo"] },
  { name: "Sweden", code: "SE", flag: "🇸🇪", timezones: ["Europe/Stockholm"] },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", timezones: ["Europe/Zurich"] },
  { name: "Syria", code: "SY", flag: "🇸🇾", timezones: ["Asia/Damascus"] },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", timezones: ["Asia/Taipei"] },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", timezones: ["Asia/Dushanbe"] },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", timezones: ["Africa/Dar_es_Salaam"] },
  { name: "Thailand", code: "TH", flag: "🇹🇭", timezones: ["Asia/Bangkok"] },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", timezones: ["Asia/Dili"] },
  { name: "Togo", code: "TG", flag: "🇹🇬", timezones: ["Africa/Lome"] },
  { name: "Tonga", code: "TO", flag: "🇹🇴", timezones: ["Pacific/Tongatapu"] },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", timezones: ["America/Port_of_Spain"] },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", timezones: ["Africa/Tunis"] },
  { name: "Turkey", code: "TR", flag: "🇹🇷", timezones: ["Europe/Istanbul"] },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", timezones: ["Asia/Ashgabat"] },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", timezones: ["Pacific/Funafuti"] },
  { name: "Uganda", code: "UG", flag: "🇺🇬", timezones: ["Africa/Kampala"] },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", timezones: ["Europe/Kyiv"] },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", timezones: ["Asia/Dubai"] },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", timezones: ["Europe/London"] },
  { name: "United States", code: "US", flag: "🇺🇸", timezones: ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Phoenix", "America/Anchorage", "Pacific/Honolulu"] },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", timezones: ["America/Montevideo"] },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", timezones: ["Asia/Tashkent"] },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", timezones: ["Pacific/Efate"] },
  { name: "Vatican City", code: "VA", flag: "🇻🇦", timezones: ["Europe/Vatican"] },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", timezones: ["America/Caracas"] },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", timezones: ["Asia/Ho_Chi_Minh"] },
  { name: "Yemen", code: "YE", flag: "🇾🇪", timezones: ["Asia/Aden"] },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", timezones: ["Africa/Lusaka"] },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", timezones: ["Africa/Harare"] },
];
