export const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", timezones: ["Asia/Kabul"] },
  { name: "Albania", code: "AL", flag: "🇦🇱", timezones: ["Europe/Tirane"] },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", timezones: ["Africa/Algiers"] },
  { name: "Argentina", code: "AR", flag: "🇦🇷", timezones: ["America/Argentina/Buenos_Aires"] },
  { name: "Australia", code: "AU", flag: "🇦🇺", timezones: ["Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane", "Australia/Perth", "Australia/Adelaide", "Australia/Darwin", "Australia/Hobart"] },
  { name: "Austria", code: "AT", flag: "🇦🇹", timezones: ["Europe/Vienna"] },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", timezones: ["Asia/Dhaka"] },
  { name: "Belgium", code: "BE", flag: "🇧🇪", timezones: ["Europe/Brussels"] },
  { name: "Brazil", code: "BR", flag: "🇧🇷", timezones: ["America/Sao_Paulo", "America/Manaus", "America/Belem", "America/Rio_Branco"] },
  { name: "Canada", code: "CA", flag: "🇨🇦", timezones: ["America/Toronto", "America/Vancouver", "America/Halifax", "America/Winnipeg", "America/Edmonton", "America/St_Johns"] },
  { name: "Chile", code: "CL", flag: "🇨🇱", timezones: ["America/Santiago"] },
  { name: "China", code: "CN", flag: "🇨🇳", timezones: ["Asia/Shanghai"] },
  { name: "Colombia", code: "CO", flag: "🇨🇴", timezones: ["America/Bogota"] },
  { name: "Croatia", code: "HR", flag: "🇭🇷", timezones: ["Europe/Zagreb"] },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", timezones: ["Europe/Prague"] },
  { name: "Denmark", code: "DK", flag: "🇩🇰", timezones: ["Europe/Copenhagen"] },
  { name: "Egypt", code: "EG", flag: "🇪🇬", timezones: ["Africa/Cairo"] },
  { name: "Estonia", code: "EE", flag: "🇪🇪", timezones: ["Europe/Tallinn"] },
  { name: "Finland", code: "FI", flag: "🇫🇮", timezones: ["Europe/Helsinki"] },
  { name: "France", code: "FR", flag: "🇫🇷", timezones: ["Europe/Paris"] },
  { name: "Germany", code: "DE", flag: "🇩🇪", timezones: ["Europe/Berlin"] },
  { name: "Greece", code: "GR", flag: "🇬🇷", timezones: ["Europe/Athens"] },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰", timezones: ["Asia/Hong_Kong"] },
  { name: "Hungary", code: "HU", flag: "🇭🇺", timezones: ["Europe/Budapest"] },
  { name: "Iceland", code: "IS", flag: "🇮🇸", timezones: ["Atlantic/Reykjavik"] },
  { name: "India", code: "IN", flag: "🇮🇳", timezones: ["Asia/Kolkata"] },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", timezones: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"] },
  { name: "Iran", code: "IR", flag: "🇮🇷", timezones: ["Asia/Tehran"] },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", timezones: ["Asia/Baghdad"] },
  { name: "Ireland", code: "IE", flag: "🇮🇪", timezones: ["Europe/Dublin"] },
  { name: "Israel", code: "IL", flag: "🇮🇱", timezones: ["Asia/Jerusalem"] },
  { name: "Italy", code: "IT", flag: "🇮🇹", timezones: ["Europe/Rome"] },
  { name: "Japan", code: "JP", flag: "🇯🇵", timezones: ["Asia/Tokyo"] },
  { name: "Jordan", code: "JO", flag: "🇯🇴", timezones: ["Asia/Amman"] },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", timezones: ["Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe"] },
  { name: "Kenya", code: "KE", flag: "🇰🇪", timezones: ["Africa/Nairobi"] },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", timezones: ["Asia/Kuwait"] },
  { name: "Latvia", code: "LV", flag: "🇱🇻", timezones: ["Europe/Riga"] },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", timezones: ["Asia/Beirut"] },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", timezones: ["Europe/Vilnius"] },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", timezones: ["Europe/Luxembourg"] },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", timezones: ["Asia/Kuala_Lumpur"] },
  { name: "Mexico", code: "MX", flag: "🇲🇽", timezones: ["America/Mexico_City", "America/Monterrey", "America/Tijuana"] },
  { name: "Morocco", code: "MA", flag: "🇲🇦", timezones: ["Africa/Casablanca"] },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", timezones: ["Europe/Amsterdam"] },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", timezones: ["Pacific/Auckland"] },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", timezones: ["Africa/Lagos"] },
  { name: "Norway", code: "NO", flag: "🇳🇴", timezones: ["Europe/Oslo"] },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", timezones: ["Asia/Karachi"] },
  { name: "Peru", code: "PE", flag: "🇵🇪", timezones: ["America/Lima"] },
  { name: "Philippines", code: "PH", flag: "🇵🇭", timezones: ["Asia/Manila"] },
  { name: "Poland", code: "PL", flag: "🇵🇱", timezones: ["Europe/Warsaw"] },
  { name: "Portugal", code: "PT", flag: "🇵🇹", timezones: ["Europe/Lisbon"] },
  { name: "Qatar", code: "QA", flag: "🇶🇦", timezones: ["Asia/Qatar"] },
  { name: "Romania", code: "RO", flag: "🇷🇴", timezones: ["Europe/Bucharest"] },
  { name: "Russia", code: "RU", flag: "🇷🇺", timezones: ["Europe/Moscow", "Asia/Yekaterinburg", "Asia/Novosibirsk", "Asia/Vladivostok"] },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", timezones: ["Asia/Riyadh"] },
  { name: "Singapore", code: "SG", flag: "🇸🇬", timezones: ["Asia/Singapore"] },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", timezones: ["Europe/Bratislava"] },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", timezones: ["Europe/Ljubljana"] },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", timezones: ["Africa/Johannesburg"] },
  { name: "South Korea", code: "KR", flag: "🇰🇷", timezones: ["Asia/Seoul"] },
  { name: "Spain", code: "ES", flag: "🇪🇸", timezones: ["Europe/Madrid"] },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", timezones: ["Asia/Colombo"] },
  { name: "Sweden", code: "SE", flag: "🇸🇪", timezones: ["Europe/Stockholm"] },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", timezones: ["Europe/Zurich"] },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", timezones: ["Asia/Taipei"] },
  { name: "Thailand", code: "TH", flag: "🇹🇭", timezones: ["Asia/Bangkok"] },
  { name: "Turkey", code: "TR", flag: "🇹🇷", timezones: ["Europe/Istanbul"] },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", timezones: ["Europe/Kyiv"] },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", timezones: ["Asia/Dubai"] },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", timezones: ["Europe/London"] },
  { name: "United States", code: "US", flag: "🇺🇸", timezones: ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Phoenix", "America/Anchorage", "Pacific/Honolulu"] },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", timezones: ["America/Montevideo"] },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", timezones: ["Asia/Tashkent"] },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", timezones: ["America/Caracas"] },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", timezones: ["Asia/Ho_Chi_Minh"] },
];
